services:
  db:
    image: postgres:15
    restart: unless-stopped
    env_file:
      - .env
    environment:
      # берём эти переменные из .env
      POSTGRES_DB:       ${POSTGRES_DB}
      POSTGRES_USER:     ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    # дождёмся БД, прогон миграций и запустим сервер
    command: >
      sh -c "
        until pg_isready -h db -p ${POSTGRES_PORT} -U ${POSTGRES_USER}; do sleep 1; done &&
        python manage.py migrate --noinput &&
        python manage.py runserver 0.0.0.0:8000
      "

volumes:
  pgdata:
